# Generated by Django 3.1.2 on 2021-05-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
