# Generated by Django 3.1.2 on 2021-05-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0002_delete_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicalls.country')),
                ('petroleum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicalls.petroleum')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicalls.year')),
            ],
        ),
    ]
