# Generated by Django 3.1.2 on 2021-05-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0003_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='petroleum',
        ),
    ]
