# Generated by Django 3.1.2 on 2021-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0005_auto_20210508_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='country',
            field=models.ManyToManyField(null=True, to='apicalls.Country'),
        ),
        migrations.AddField(
            model_name='main',
            name='petroleum',
            field=models.ManyToManyField(null=True, to='apicalls.Petroleum'),
        ),
        migrations.AddField(
            model_name='main',
            name='year',
            field=models.ManyToManyField(null=True, to='apicalls.Year'),
        ),
    ]
