# Generated by Django 3.1.2 on 2021-05-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0006_auto_20210508_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='country',
        ),
        migrations.AddField(
            model_name='main',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apicalls.country'),
        ),
        migrations.RemoveField(
            model_name='main',
            name='petroleum',
        ),
        migrations.AddField(
            model_name='main',
            name='petroleum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apicalls.petroleum'),
        ),
        migrations.RemoveField(
            model_name='main',
            name='year',
        ),
        migrations.AddField(
            model_name='main',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apicalls.year'),
        ),
    ]
