# Generated by Django 3.1.2 on 2021-05-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0010_twoyearinterval_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='leastyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leastsale', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicalls.petroleum')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apicalls.year')),
            ],
        ),
    ]
